### ISSUE TITLE
outstanding validation errors

### ISSUE THREAD

**Issue by duncdrum** [BetaMasaheft/corpora#3]
none of the `corpus*.xml` files in this repo are valid. I m not sure what the desired or required format of the information is here. 

1. each file has a `teiCorpus` root element without a namespace declaration. This element must be in the tei namespace. 
2. A `teiCorpus` element is intended to collect multiple `TEI` element children, but each file has only one. So it appears superfluous
3. None of the `TEI` elements has a `body` element, so I m not sure what the `TEI/teiHeader` is intended to describe. 
4. A `teiCorpus` element [*must*](https://tei-c.org/release/doc/tei-p5-doc/de/html/ref-teiCorpus.html) have its own teiHeader, e.g.
```xml
<teiCorpus xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>[…]</teiHeader>
  <TEI>
     <teiHeader>[…]</teiHeader>
     <body>[…]</body>
  </TEI>
  <TEI>[…]</TEI>
</teiCorpus>
```

to be able to validate these 12 files, some refactoring by the project will be necessary.

**Comment by eu-genia** [comment]
These are external data, from another project. The corpora themselves have never been adjusted (e.g. they use their own internal links to mss etc)... I actually did not want to touch `external `data in principle... 

There are actually manuscripts (or rather items inside of one manuscript for the moment, BNFabb152) in the `Manuscripts `repo that belong to (one of) these corpora, 
```
<relation active="BNFabb152#a1" name="saws:formsPartOf" passive="corpus3"/>
<relation active="BNFabb152#a2" name="saws:formsPartOf" passive="corpus3"/>
```
They used to be visualized on the live app (there used to be a page `documentcorpora.html` calling on `lists:corpora `from `resources.xqm` but it is not active https://github.com/BetaMasaheft/Documentation/issues/2133 
The code does look for `:teiCorpus `so we cannot take out the element

I guess there was some creative encoding/understanding of TEI involved: the current `corpora `files contain in fact the `teiHeader `for the corpus as corpus-related metadata, but the actual corpus elements are not TEI elements inside of the corpus files, but the items dispersed among different manuscripts described and currently linked via `relation`.

So actually the true fix would be to have
```
<teiCorpus xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>CURRENT FILE AS IT IS</teiHeader>
  <TEI>
     <teiHeader>????? some placeholder</teiHeader>
     <body>??? some sort of xi:include??? of the relevant element(s)???</body>
  </TEI>
  <TEI>[…]</TEI>
</teiCorpus>
```
but this is out of my reach and beyond our scope.

I can add after each teiHeader an empty TEI element 

```
<teiCorpus xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>CURRENT FILE AS IT IS</teiHeader>
<TEI>
    <teiHeader>
      <fileDesc><titleStmt>
        <title></title>
      </titleStmt>
      <publicationStmt><ab/></publicationStmt>
      <sourceDesc><ab/></sourceDesc></fileDesc>
    </teiHeader>
    <text>
     <body><ab/></body>
    </text>
  </TEI>
</teiCorpus>
```
as tried here https://github.com/BetaMasaheft/corpora/compare/main...adding-empty-tei - this file looks valid with tei-all in my Oxygen but of course this is not handsome...

Should I?

****

At the moment there is no webhook set up for changes in `corpora `on github to go to the live app - but of course the files are few, so i can also upload them manually once they are changed. (If we do the same workflow as for others the default branch should also be renamed as `master`)

**Comment by eu-genia** [comment]
just noticed that my fix (involving rebasing teiCorpus and moving the id to teiCorpus) does not work fine with the code which for the moment looks for the `xml:id `of` t:TEI`
`1306 let $id := string($corpus//t:TEI/@xml:id)
`
but maybe it is better to correct in the xquery to 
`1306 let $id := string($corpus//teiCorpus/@xml:id)
`
as otherwise it does not seem to make sense

**Comment by eu-genia** [comment]
alternatively, since the xquery has to be changed in any case, one could also get rid of teiCorpus, probably even nicer.
then one could take this version https://github.com/BetaMasaheft/corpora/pull/4 and then I would change
`1306 for $corpus in collection($config:data-root || '/corpora')//*:teiCorpus
`to 
`1306 for $corpus in collection($config:data-root || '/corpora')//*:TEI`

*****


so i prepared two PRs, both validating, both requesting code update
https://github.com/BetaMasaheft/corpora/pull/4 (then teiCorpus has to be changed to TEI)
https://github.com/BetaMasaheft/corpora/pull/5 (then xml:id location should be updated)

you decide which is the better way

**Comment by eu-genia** [comment]
I see now that both PRs report errors; my Oxygen is all green so I cannot fix them ...

**Comment by eu-genia** [comment]
I am not sure whether the problem is with the data or with the `xmllint `validation, but there is no way for me to get them pass the test...

In order to find out what's wrong I have now tried to create a clean minimal record from the Oxygen template as suggested (test.xml) but it fails the test with the same message as the other files in the branch `Relax-NG validity error : Element TEI failed to validate attributes` (the others also have the error with the `change `element, but if this were the only problem left I would have commented it out `element change: Relax-NG validity error : Element change failed to validate attributes`) https://github.com/BetaMasaheft/corpora/actions/runs/3200482055/jobs/5227430646

I did  the same test also in https://github.com/BetaMasaheft/corpora/pull/5 by pushing a clean record from the template and again got the same response for `test.xml` as for the other files in the branch (`Relax-NG validity error : Did not expect element teiCorpus there`)

**Comment by duncdrum** [comment]
@eu-genia xmlint is not the problem. From the looks of it you are validating against `tei_allPlus.rng` in Oxygen, which is now all valid in #6. 

```shell
xmllint --noout --relaxng schema/tei_allPlus.rng corpus*.xml 
corpus10.xml validates
corpus11.xml validates
corpus12.xml validates
corpus13.xml validates
corpus14.xml validates
corpus2.xml validates
corpus3.xml validates
corpus4.xml validates
corpus5.xml validates
corpus7.xml validates
corpus8.xml validates
corpus9.xml validates
```

However, the CI is configured to validate against *your* schema `tei-betamesaheft.rng`

```
element "TEI" missing required attribute "type"
element "change" missing required attribute "who"
element "roleName" missing required attribute "type"
```

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/corpora/pull/6
